# Site settings
title: "Manste blog"
SEOTitle: Blog de Manuelle Ndamtang
header-img: img/post-bg-desk.jpg
email: manuelle.ndamtang@goossens-network.be
description: "Pourquoi se contenter d'une vie simple quand on peut se challenger..."
keyword: "Manste Blog, Cybersecurité, Data Science, DevSecOps, Cloud"
url: "http://manste.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Manste/manste.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Ici on apprend, on se challenge, on apporte des resultats concrets!"
sidebar-avatar: https://media.licdn.com/dms/image/v2/C4D03AQGcPJOGf8_Mvg/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1593035778874?e=1760572800&v=beta&t=QCLSVEiyzSm81W9hzZuV8uQRL0jITkGh8V6Rrx7v4jo    # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
linkedin_username:  manuelle-ndamtang
github_username:    manste
youtube_username:   manuelle-ndamtang
twitter_username:   manuelle-ndamtang




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


# Gitalk
gitalk:
  enable: true   
  clientID: Ov23liaQXu5cHhBxumrw                           
  clientSecret: 06a87e604498feccd88fbc9372ae83625d54a805
  repo: manste.github.io   
  owner: Manste   
  admin: Manste
  distractionFreeMode: true 




# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'G-EGY1ZVEFYY'            
ga_domain: auto





# Featured Tags
featured-tags: true                     
featured-condition-size: 1              



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
#friends: [
#    {
#        title: "WY",
#        href: "http://zhengwuyang.com"
#    },{
#        title: "简书·BY",
#        href: "http://www.jianshu.com/u/e71990ada2fd"
#    },{
#        title: "Apple",
#        href: "https://apple.com"
#    },{
#        title: "Apple Developer",
#        href: "https://developer.apple.com/"
#    }
#]
